
import dotenv from 'dotenv'
import mongoose from 'mongoose'
import Product from '../model/productModel.js'
import connectDb from '../config/db.js'

dotenv.config()

async function addFlipkartProducts() {
  try {
    await connectDb();

    const flipkartProducts = [
      // Electronics - Mobile Phones (5 products)
      {
        name: "Samsung Galaxy M14 5G",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/6/2/1/-original-imagzjhw9p8pdtft.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/6/2/1/-original-imagzjhw9p8pdtft.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/6/2/1/-original-imagzjhw9p8pdtft.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/6/2/1/-original-imagzjhw9p8pdtft.jpeg?q=70",
        description: "Samsung Galaxy M14 5G (ICY Silver, 4GB, 128GB Storage) | 50MP Triple Cam | 6000 mAh Battery | 5nm Octa-Core Processor | Android 13 | Without Charger",
        price: 14990,
        category: "Electronics",
        subCategory: "Mobile Phones",
        sizes: ["128GB"],
        date: Date.now(),
        bestseller: true,
        discount: 10,
        isManual: true
      },
      {
        name: "Redmi 12C",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/q/g/b/-original-imagzeyy3bmgc7n8.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/q/g/b/-original-imagzeyy3bmgc7n8.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/q/g/b/-original-imagzeyy3bmgc7n8.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/q/g/b/-original-imagzeyy3bmgc7n8.jpeg?q=70",
        description: "Redmi 12C (Matte Black, 4GB RAM, 64GB Storage) | High Performance Mediatek Helio G85 | Big 17cm(6.71) HD+ Display with 5000mAh Battery",
        price: 8999,
        category: "Electronics",
        subCategory: "Mobile Phones",
        sizes: ["64GB"],
        date: Date.now(),
        bestseller: true,
        discount: 5,
        isManual: true
      },
      {
        name: "OnePlus Nord CE 3 Lite 5G",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/y/l/t/-original-imagtxvths6q7xgz.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/y/l/t/-original-imagtxvths6q7xgz.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/y/l/t/-original-imagtxvths6q7xgz.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/y/l/t/-original-imagtxvths6q7xgz.jpeg?q=70",
        description: "OnePlus Nord CE 3 Lite 5G (Chromatic Gray, 8GB RAM, 128GB Storage) | Snapdragon 782G Processor | 120Hz AMOLED Display | 5000mAh Battery",
        price: 19999,
        category: "Electronics",
        subCategory: "Mobile Phones",
        sizes: ["128GB"],
        date: Date.now(),
        bestseller: false,
        discount: 8,
        isManual: true
      },
      {
        name: "Apple iPhone 15",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/k/l/l/-original-imagtc5fz9spysyk.jpeg?q=70",
        description: "Apple iPhone 15 (Black, 128 GB) | Dynamic Island | 48MP Main Camera | 4K 60fps Dolby Vision HDR Video",
        price: 79900,
        category: "Electronics",
        subCategory: "Mobile Phones",
        sizes: ["128GB"],
        date: Date.now(),
        bestseller: true,
        discount: 5,
        isManual: true
      },
      {
        name: "Vivo Y100",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/m/u/-original-imagtt4szyy8yzbk.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/m/u/-original-imagtt4szyy8yzbk.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/m/u/-original-imagtt4szyy8yzbk.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/x/m/u/-original-imagtt4szyy8yzbk.jpeg?q=70",
        description: "Vivo Y100 (Pacific Blue, 8GB RAM, 128GB Storage) | Snapdragon 685 Processor | 64MP OIS Camera | 5000mAh Battery",
        price: 24999,
        category: "Electronics",
        subCategory: "Mobile Phones",
        sizes: ["128GB"],
        date: Date.now(),
        bestseller: false,
        discount: 12,
        isManual: true
      },

      // Electronics - Headphones (5 products)
      {
        name: "boAt Rockerz 255 Pro+",
        image1: "https://rukminim2.flixcart.com/image/612/612/ktszgy80/headphone/0/k/r/rockerz-255-pro-boat-original-imag72w9p7mxmg7g.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/ktszgy80/headphone/0/k/r/rockerz-255-pro-boat-original-imag72w9p7mxmg7g.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/ktszgy80/headphone/0/k/r/rockerz-255-pro-boat-original-imag72w9p7mxmg7g.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/ktszgy80/headphone/0/k/r/rockerz-255-pro-boat-original-imag72w9p7mxmg7g.jpeg?q=70",
        description: "boAt Rockerz 255 Pro+ in-Ear Earphones with 10mm Drivers, Up to 40H Playtime, ASAP Charge, IPX5, Bluetooth 5.2 & ENx Tech (Active Black)",
        price: 1299,
        category: "Electronics",
        subCategory: "Headphones",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: false,
        discount: 15,
        isManual: true
      },
      {
        name: "Sony WH-1000XM5",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/3/7/-original-imagzy3g3h9eztv6.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/3/7/-original-imagzy3g3h9eztv6.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/3/7/-original-imagzy3g3h9eztv6.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/3/7/-original-imagzy3g3h9eztv6.jpeg?q=70",
        description: "Sony WH-1000XM5 Wireless Premium Noise Canceling Overhead Headphones with Mic (Black) | Industry Leading Noise Cancellation",
        price: 29990,
        category: "Electronics",
        subCategory: "Headphones",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: false,
        discount: 12,
        isManual: true
      },
      {
        name: "JBL T600BTNC",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/z/7/-original-imagz6g2hugfykxz.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/z/7/-original-imagz6g2hugfykxz.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/z/7/-original-imagz6g2hugfykxz.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/7/z/7/-original-imagz6g2hugfykxz.jpeg?q=70",
        description: "JBL T600BTNC Wireless On Ear Headphones with Mic, Pure Bass Sound, Quick Charge, Voice Assistant Support for Mobiles (Black)",
        price: 2999,
        category: "Electronics",
        subCategory: "Headphones",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: true,
        discount: 20,
        isManual: true
      },
      {
        name: "Marshall Major III Bluetooth",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/0/3/2/-original-imagz4wxahf8zgcy.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/0/3/2/-original-imagz4wxahf8zgcy.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/0/3/2/-original-imagz4wxahf8zgcy.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/0/3/2/-original-imagz4wxahf8zgcy.jpeg?q=70",
        description: "Marshall Major III Bluetooth Wireless On Ear Headphones with Mic (Black) | 80Hrs Playtime | Premium Sound Quality",
        price: 11999,
        category: "Electronics",
        subCategory: "Headphones",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: false,
        discount: 8,
        isManual: true
      },
      {
        name: "Realme Buds Wireless 3",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/8/9/-original-imagz3g8gugskc3z.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/8/9/-original-imagz3g8gugskc3z.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/8/9/-original-imagz3g8gugskc3z.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/headphone/y/8/9/-original-imagz3g8gugskc3z.jpeg?q=70",
        description: "Realme Buds Wireless 3 with 30dB ANC, 30Hrs Playtime, 360 Spatial Audio, Fast Charging, Bluetooth 5.3 (Black)",
        price: 2499,
        category: "Electronics",
        subCategory: "Headphones",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: true,
        discount: 25,
        isManual: true
      },

      // Electronics - Smartwatches (5 products)
      {
        name: "Noise ColorFit Pro 4",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/k/-original-imagkgrxgwzrjg8y.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/k/-original-imagkgrxgwzrjg8y.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/k/-original-imagkgrxgwzrjg8y.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/k/-original-imagkgrxgwzrjg8y.jpeg?q=70",
        description: "Noise ColorFit Pro 4 Alpha 1.78'' AMOLED Display, 60 Sports Modes, 10 Days Battery Life, SPO2 & Heart Rate Monitoring Smartwatch (Jet Black)",
        price: 3499,
        category: "Electronics",
        subCategory: "Smartwatches",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: true,
        discount: 20,
        isManual: true
      },
      {
        name: "Fire-Boltt Ninja Call Pro Plus",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/v/t/6/-original-imagz3gznhhmcghy.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/v/t/6/-original-imagz3gznhhmcghy.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/v/t/6/-original-imagz3gznhhmcghy.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/v/t/6/-original-imagz3gznhhmcghy.jpeg?q=70",
        description: "Fire-Boltt Ninja Call Pro Plus 1.83'' Smart Watch with Bluetooth Calling, AI Voice Assistant, 100 Sports Modes, 240 * 280 Pixel High Resolution (Black)",
        price: 1799,
        category: "Electronics",
        subCategory: "Smartwatches",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: false,
        discount: 30,
        isManual: true
      },
      {
        name: "Samsung Galaxy Watch5",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/9/n/k/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/9/n/k/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/9/n/k/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/9/n/k/-original-imagzcg8hgggfgdj.jpeg?q=70",
        description: "Samsung Galaxy Watch5 Bluetooth(40mm, Graphite, Compatible with Android only) | Advanced Health Monitoring | 40mm AMOLED Display",
        price: 22999,
        category: "Electronics",
        subCategory: "Smartwatches",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: false,
        discount: 15,
        isManual: true
      },
      {
        name: "Apple Watch SE",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/j/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/j/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/j/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/y/t/j/-original-imagzcg8hgggfgdj.jpeg?q=70",
        description: "Apple Watch SE (GPS, 40mm) - Starlight Aluminium Case with Starlight Sport Band | Advanced Health & Safety Features",
        price: 29900,
        category: "Electronics",
        subCategory: "Smartwatches",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: true,
        discount: 10,
        isManual: true
      },
      {
        name: "Amazfit GTR 4",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/8/9/8/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/8/9/8/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/8/9/8/-original-imagzcg8hgggfgdj.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/smartwatch/8/9/8/-original-imagzcg8hgggfgdj.jpeg?q=70",
        description: "Amazfit GTR 4 Smart Watch with 1.43'' AMOLED Display, 150+ Sports Modes, 24Hrs Heart Rate Monitoring, 14 Days Battery Life (Black)",
        price: 12999,
        category: "Electronics",
        subCategory: "Smartwatches",
        sizes: ["One Size"],
        date: Date.now(),
        bestseller: false,
        discount: 18,
        isManual: true
      },

      // Electronics - Laptops (5 products)
      {
        name: "Dell Inspiron 15",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/e/z/-original-imagzvfaxfzk3vvs.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/e/z/-original-imagzvfaxfzk3vvs.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/e/z/-original-imagzvfaxfzk3vvs.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/e/z/-original-imagzvfaxfzk3vvs.jpeg?q=70",
        description: "Dell Inspiron 3520 Laptop, Intel Core i3-1215U, 8GB & 512GB SSD, 15.6 (39.62cm) FHD Display, Win 11+MSO'21, Carbon Black, 1.65Kgs",
        price: 38990,
        category: "Electronics",
        subCategory: "Laptops",
        sizes: ["512GB"],
        date: Date.now(),
        bestseller: true,
        discount: 8,
        isManual: true
      },
      {
        name: "HP Pavilion 14",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/5/6/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/5/6/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/5/6/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/5/6/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        description: "HP Pavilion 14, 12th Gen Intel Core i5, 16GB RAM, 512GB SSD, 14 inch(35.6 cm) FHD Screen, Win 11, MSO, Ceramic White, 1.41kg",
        price: 64990,
        category: "Electronics",
        subCategory: "Laptops",
        sizes: ["512GB"],
        date: Date.now(),
        bestseller: false,
        discount: 12,
        isManual: true
      },
      {
        name: "Lenovo IdeaPad 3",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/n/i/u/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/n/i/u/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/n/i/u/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/n/i/u/-original-imagzfc5wtzqjubk.jpeg?q=70",
        description: "Lenovo IdeaPad 3 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) 15ITL6 Thin and Light Laptop (15.6 Inch, Arctic Grey, 1.7 kg kg)",
        price: 35990,
        category: "Electronics",
        subCategory: "Laptops",
        sizes: ["512GB"],
        date: Date.now(),
        bestseller: true,
        discount: 15,
        isManual: true
      },
      {
        name: "ASUS VivoBook 15",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/5/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/5/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/5/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/q/5/7/-original-imagzfc5wtzqjubk.jpeg?q=70",
        description: "ASUS VivoBook 15 Intel Core i5 11th Gen 1135G7 - (8 GB/512 GB SSD/Windows 11 Home) X515EA-EJ522WS Thin and Light Laptop (15.6 Inch, Transparent Silver, 1.8 kg)",
        price: 49990,
        category: "Electronics",
        subCategory: "Laptops",
        sizes: ["512GB"],
        date: Date.now(),
        bestseller: false,
        discount: 10,
        isManual: true
      },
      {
        name: "Acer Aspire 5",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/0/0/0/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/0/0/0/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/0/0/0/-original-imagzfc5wtzqjubk.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/computer/0/0/0/-original-imagzfc5wtzqjubk.jpeg?q=70",
        description: "Acer Aspire 5 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) A515-57 Thin and Light Laptop (15.6 Inch, Steel Gray, 1.76 Kg)",
        price: 42990,
        category: "Electronics",
        subCategory: "Laptops",
        sizes: ["512GB"],
        date: Date.now(),
        bestseller: false,
        discount: 6,
        isManual: true
      },

      // Electronics - Televisions (5 products)
      {
        name: "Samsung 32 inch LED TV",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/z/z/z/-original-imagttjpr7vphrks.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/z/z/z/-original-imagttjpr7vphrks.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/z/z/z/-original-imagttjpr7vphrks.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/z/z/z/-original-imagttjpr7vphrks.jpeg?q=70",
        description: "SAMSUNG 32T4380 32 inch HD Ready LED Smart TV with Voice Search | HDR | PurColor | Dolby Digital Plus | SmartThings App",
        price: 18990,
        category: "Electronics",
        subCategory: "Televisions",
        sizes: ["32 inch"],
        date: Date.now(),
        bestseller: false,
        discount: 15,
        isManual: true
      },
      {
        name: "LG 43 inch LED TV",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/j/l/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/j/l/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/j/l/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/j/l/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        description: "LG 43 inch UHD 4K LED Smart TV | WebOS | Magic Remote | ThinQ AI | HDR | 4K Upscaling | 60Hz Refresh Rate",
        price: 34990,
        category: "Electronics",
        subCategory: "Televisions",
        sizes: ["43 inch"],
        date: Date.now(),
        bestseller: true,
        discount: 10,
        isManual: true
      },
      {
        name: "Sony Bravia 55 inch OLED TV",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/x/8/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/x/8/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/x/8/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/x/8/3/-original-imagzprbgzxnhfke.jpeg?q=70",
        description: "Sony Bravia 55 inch OLED 4K Ultra HD Smart Google TV | XR Triluminos Pro | XR OLED Contrast Pro | XR 4K Upscaling",
        price: 89990,
        category: "Electronics",
        subCategory: "Televisions",
        sizes: ["55 inch"],
        date: Date.now(),
        bestseller: false,
        discount: 8,
        isManual: true
      },
      {
        name: "Mi 4A Horizon Edition 32 inch LED TV",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/9/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/9/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/9/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/9/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        description: "Mi 4A Horizon Edition 32 inch HD Ready LED Smart Android TV with Dolby Audio (2024 Model)",
        price: 15990,
        category: "Electronics",
        subCategory: "Televisions",
        sizes: ["32 inch"],
        date: Date.now(),
        bestseller: true,
        discount: 20,
        isManual: true
      },
      {
        name: "OnePlus 50 inch QLED TV",
        image1: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/0/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/0/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/0/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/312/312/xif0q/television/0/0/0/-original-imagzprbgzxnhfke.jpeg?q=70",
        description: "OnePlus 50U1S 50 inch UHD 4K LED Smart Android TV with Dolby Audio | 60Hz Refresh Rate | HDR10+ | Gamma Engine",
        price: 39990,
        category: "Electronics",
        subCategory: "Televisions",
        sizes: ["50 inch"],
        date: Date.now(),
        bestseller: false,
        discount: 12,
        isManual: true
      },

      // Fashion - Shoes (5 products)
      {
        name: "Nike Air Max 270",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/8/z/j/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/8/z/j/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/8/z/j/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/8/z/j/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        description: "Nike Air Max 270 Men's Shoes | Nike Air Technology | Breathable Mesh Upper | Rubber Outsole | Black/White",
        price: 11995,
        category: "Fashion",
        subCategory: "Shoes",
        sizes: ["7", "8", "9", "10", "11"],
        date: Date.now(),
        bestseller: true,
        discount: 10,
        isManual: true
      },
      {
        name: "Adidas Ultraboost 22",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/5/z/8/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/5/z/8/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/5/z/8/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/5/z/8/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        description: "Adidas Ultraboost 22 Running Shoes | Boost Technology | Continental Rubber Outsole | Cloudfoam Sockliner | Black",
        price: 18999,
        category: "Fashion",
        subCategory: "Shoes",
        sizes: ["7", "8", "9", "10", "11", "12"],
        date: Date.now(),
        bestseller: false,
        discount: 20,
        isManual: true
      },
      {
        name: "Puma RS-X Toys",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/z/8/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/z/8/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/z/8/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/d/z/8/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        description: "Puma RS-X Toys Men's Sneakers | Retro Style | Comfortable Cushioning | Durable Rubber Outsole | White/Black",
        price: 8999,
        category: "Fashion",
        subCategory: "Shoes",
        sizes: ["6", "7", "8", "9", "10", "11"],
        date: Date.now(),
        bestseller: true,
        discount: 15,
        isManual: true
      },
      {
        name: "Reebok Nano X3",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/2/3/4/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/2/3/4/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/2/3/4/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/2/3/4/-original-imagz8zhbhzhyhbx.jpeg?q=70",
        description: "Reebok Nano X3 Training Shoes | Hexalite Technology | Speed Cage | Flex Groove Outsole | Black/White",
        price: 12999,
        category: "Fashion",
        subCategory: "Shoes",
        sizes: ["7", "8", "9", "10", "11", "12"],
        date: Date.now(),
        bestseller: false,
        discount: 12,
        isManual: true
      },
      {
        name: "New Balance 574",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/1/2/3/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/1/2/3/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/1/2/3/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/shoe/1/2/3/-original-imagz7b8hbxzpyhn.jpeg?q=70",
        description: "New Balance 574 Classic Sneakers | ENCAP Midsole | Heritage Style | Comfortable Fit | Navy/White",
        price: 7999,
        category: "Fashion",
        subCategory: "Shoes",
        sizes: ["6", "7", "8", "9", "10", "11"],
        date: Date.now(),
        bestseller: true,
        discount: 8,
        isManual: true
      },

      // Fashion - Clothing (5 products)
      {
        name: "Levi's Men's Slim Fit Jeans",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/2/q/g/32-18298-1258-levi-s-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/2/q/g/32-18298-1258-levi-s-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/2/q/g/32-18298-1258-levi-s-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/jean/2/q/g/32-18298-1258-levi-s-original-imagz8zhbhzhyhbx.jpeg?q=70",
        description: "Levi's Men's Slim Fit Jeans | 511 Skinny Fit | Stretchable Denim | 5-Pocket Design | Dark Blue",
        price: 2999,
        category: "Fashion",
        subCategory: "Clothing",
        sizes: ["28", "30", "32", "34", "36"],
        date: Date.now(),
        bestseller: true,
        discount: 20,
        isManual: true
      },
      {
        name: "H&M Cotton T-Shirt",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/v/k/m-oversizedtshirt-white-hm-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/v/k/m-oversizedtshirt-white-hm-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/v/k/m-oversizedtshirt-white-hm-original-imagz7b8hbxzpyhn.jpeg?q=70",
        image4: "https://rukminim2.flixcart.com/image/612/612/xif0q/t-shirt/r/v/k/m-oversizedtshirt-white-hm-original-imagz7b8hbxzpyhn.jpeg?q=70",
        description: "H&M Oversized Cotton T-Shirt | Regular Fit | Crew Neck | Short Sleeve | White",
        price: 1299,
        category: "Fashion",
        subCategory: "Clothing",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 10,
        isManual: true
      },
      {
        name: "Nike Sportswear Club Fleece Hoodie",
        image1: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/u/z/c/l-nkfsj5596-001-nike-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image2: "https://rukminim2.flixcart.com/image/612/612/xif0q/sweatshirt/u/z/c/l-nkfsj5596-001-nike-original-imagz8zhbhzhyhbx.jpeg?q=70",
        image3: "https://rukminim2.flixcart.com/image/612/612/x