
import dotenv from 'dotenv'
import mongoose from 'mongoose'
import Product from '../model/productModel.js'
import connectDb from '../config/db.js'

dotenv.config()

async function addNewProducts() {
  try {
    await connectDb();

    const newProducts = [
      {
        name: "Mens Shirt",
        image1: "https://source.unsplash.com/600x600/?mens,shirt",
        image2: "https://source.unsplash.com/600x600/?mens,shirt,product",
        image3: "https://source.unsplash.com/600x600/?mens,shirt,studio",
        image4: "https://source.unsplash.com/600x600/?mens,shirt,closeup",
        description: "Mens Shirt: High-quality mens shirt designed for everyday use with excellent durability and comfort.",
        price: 649,
        category: "Clothes",
        subCategory: "TopWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Womens Dress",
        image1: "https://source.unsplash.com/600x600/?womens,dress",
        image2: "https://source.unsplash.com/600x600/?womens,dress,product",
        image3: "https://source.unsplash.com/600x600/?womens,dress,studio",
        image4: "https://source.unsplash.com/600x600/?womens,dress,closeup",
        description: "Womens Dress: High-quality womens dress designed for everyday use with excellent durability and comfort.",
        price: 2049,
        category: "Clothes",
        subCategory: "TopWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Denim Jeans Pro",
        image1: "https://source.unsplash.com/600x600/?denim,jeans",
        image2: "https://source.unsplash.com/600x600/?denim,jeans,product",
        image3: "https://source.unsplash.com/600x600/?denim,jeans,studio",
        image4: "https://source.unsplash.com/600x600/?denim,jeans,closeup",
        description: "Denim Jeans Pro: High-quality denim jeans designed for everyday use with excellent durability and comfort.",
        price: 4799,
        category: "Clothes",
        subCategory: "BottomWear",
        sizes: ["28", "30", "32", "34", "36"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Woolen Sweater",
        image1: "https://source.unsplash.com/600x600/?woolen,sweater",
        image2: "https://source.unsplash.com/600x600/?woolen,sweater,product",
        image3: "https://source.unsplash.com/600x600/?woolen,sweater,studio",
        image4: "https://source.unsplash.com/600x600/?woolen,sweater,closeup",
        description: "Woolen Sweater: High-quality woolen sweater designed for everyday use with excellent durability and comfort.",
        price: 3949,
        category: "Clothes",
        subCategory: "WinterWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Premium Polo Tshirt",
        image1: "https://source.unsplash.com/600x600/?polo,tshirt",
        image2: "https://source.unsplash.com/600x600/?polo,tshirt,product",
        image3: "https://source.unsplash.com/600x600/?polo,tshirt,studio",
        image4: "https://source.unsplash.com/600x600/?polo,tshirt,closeup",
        description: "Premium Polo Tshirt: High-quality polo tshirt designed for everyday use with excellent durability and comfort.",
        price: 699,
        category: "Clothes",
        subCategory: "TopWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Kurti Plus",
        image1: "https://source.unsplash.com/600x600/?kurti",
        image2: "https://source.unsplash.com/600x600/?kurti,product",
        image3: "https://source.unsplash.com/600x600/?kurti,studio",
        image4: "https://source.unsplash.com/600x600/?kurti,closeup",
        description: "Kurti Plus: High-quality kurti designed for everyday use with excellent durability and comfort.",
        price: 1949,
        category: "Clothes",
        subCategory: "TopWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Hoodie Pro",
        image1: "https://source.unsplash.com/600x600/?hoodie",
        image2: "https://source.unsplash.com/600x600/?hoodie,product",
        image3: "https://source.unsplash.com/600x600/?hoodie,studio",
        image4: "https://source.unsplash.com/600x600/?hoodie,closeup",
        description: "Hoodie Pro: High-quality hoodie designed for everyday use with excellent durability and comfort.",
        price: 4049,
        category: "Clothes",
        subCategory: "WinterWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Denim Jacket (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?denim,jacket",
        image2: "https://source.unsplash.com/600x600/?denim,jacket,product",
        image3: "https://source.unsplash.com/600x600/?denim,jacket,studio",
        image4: "https://source.unsplash.com/600x600/?denim,jacket,closeup",
        description: "Denim Jacket (2025 Model): High-quality denim jacket designed for everyday use with excellent durability and comfort.",
        price: 3149,
        category: "Clothes",
        subCategory: "WinterWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Formal Suit (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?formal,suit",
        image2: "https://source.unsplash.com/600x600/?formal,suit,product",
        image3: "https://source.unsplash.com/600x600/?formal,suit,studio",
        image4: "https://source.unsplash.com/600x600/?formal,suit,closeup",
        description: "Formal Suit (2025 Model): High-quality formal suit designed for everyday use with excellent durability and comfort.",
        price: 2249,
        category: "Clothes",
        subCategory: "TopWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Casual Top",
        image1: "https://source.unsplash.com/600x600/?casual,top",
        image2: "https://source.unsplash.com/600x600/?casual,top,product",
        image3: "https://source.unsplash.com/600x600/?casual,top,studio",
        image4: "https://source.unsplash.com/600x600/?casual,top,closeup",
        description: "Casual Top: High-quality casual top designed for everyday use with excellent durability and comfort.",
        price: 499,
        category: "Clothes",
        subCategory: "TopWear",
        sizes: ["S", "M", "L", "XL", "XXL"],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Laptop",
        image1: "https://source.unsplash.com/600x600/?laptop",
        image2: "https://source.unsplash.com/600x600/?laptop,product",
        image3: "https://source.unsplash.com/600x600/?laptop,studio",
        image4: "https://source.unsplash.com/600x600/?laptop,closeup",
        description: "Laptop: High-quality laptop designed for everyday use with excellent durability and comfort.",
        price: 8949,
        category: "Electronics",
        subCategory: "Laptops",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Smartphone",
        image1: "https://source.unsplash.com/600x600/?smartphone",
        image2: "https://source.unsplash.com/600x600/?smartphone,product",
        image3: "https://source.unsplash.com/600x600/?smartphone,studio",
        image4: "https://source.unsplash.com/600x600/?smartphone,closeup",
        description: "Smartphone: High-quality smartphone designed for everyday use with excellent durability and comfort.",
        price: 18199,
        category: "Electronics",
        subCategory: "Phones",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Wireless Earbuds Plus",
        image1: "https://source.unsplash.com/600x600/?wireless,earbuds",
        image2: "https://source.unsplash.com/600x600/?wireless,earbuds,product",
        image3: "https://source.unsplash.com/600x600/?wireless,earbuds,studio",
        image4: "https://source.unsplash.com/600x600/?wireless,earbuds,closeup",
        description: "Wireless Earbuds Plus: High-quality wireless earbuds designed for everyday use with excellent durability and comfort.",
        price: 39849,
        category: "Electronics",
        subCategory: "Audio",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Smart Watch Pro",
        image1: "https://source.unsplash.com/600x600/?smart,watch",
        image2: "https://source.unsplash.com/600x600/?smart,watch,product",
        image3: "https://source.unsplash.com/600x600/?smart,watch,studio",
        image4: "https://source.unsplash.com/600x600/?smart,watch,closeup",
        description: "Smart Watch Pro: High-quality smart watch designed for everyday use with excellent durability and comfort.",
        price: 20249,
        category: "Electronics",
        subCategory: "Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Bluetooth Speaker - Classic",
        image1: "https://source.unsplash.com/600x600/?bluetooth,speaker",
        image2: "https://source.unsplash.com/600x600/?bluetooth,speaker,product",
        image3: "https://source.unsplash.com/600x600/?bluetooth,speaker,studio",
        image4: "https://source.unsplash.com/600x600/?bluetooth,speaker,closeup",
        description: "Bluetooth Speaker - Classic: High-quality bluetooth speaker designed for everyday use with excellent durability and comfort.",
        price: 31699,
        category: "Electronics",
        subCategory: "Audio",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Dslr Camera Pro",
        image1: "https://source.unsplash.com/600x600/?dslr,camera",
        image2: "https://source.unsplash.com/600x600/?dslr,camera,product",
        image3: "https://source.unsplash.com/600x600/?dslr,camera,studio",
        image4: "https://source.unsplash.com/600x600/?dslr,camera,closeup",
        description: "Dslr Camera Pro: High-quality dslr camera designed for everyday use with excellent durability and comfort.",
        price: 38149,
        category: "Electronics",
        subCategory: "Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Gaming Headset Pro",
        image1: "https://source.unsplash.com/600x600/?gaming,headset",
        image2: "https://source.unsplash.com/600x600/?gaming,headset,product",
        image3: "https://source.unsplash.com/600x600/?gaming,headset,studio",
        image4: "https://source.unsplash.com/600x600/?gaming,headset,closeup",
        description: "Gaming Headset Pro: High-quality gaming headset designed for everyday use with excellent durability and comfort.",
        price: 20149,
        category: "Electronics",
        subCategory: "Audio",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Portable Charger - Classic",
        image1: "https://source.unsplash.com/600x600/?portable,charger",
        image2: "https://source.unsplash.com/600x600/?portable,charger,product",
        image3: "https://source.unsplash.com/600x600/?portable,charger,studio",
        image4: "https://source.unsplash.com/600x600/?portable,charger,closeup",
        description: "Portable Charger - Classic: High-quality portable charger designed for everyday use with excellent durability and comfort.",
        price: 43249,
        category: "Electronics",
        subCategory: "Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "4K Monitor",
        image1: "https://source.unsplash.com/600x600/?4k,monitor",
        image2: "https://source.unsplash.com/600x600/?4k,monitor,product",
        image3: "https://source.unsplash.com/600x600/?4k,monitor,studio",
        image4: "https://source.unsplash.com/600x600/?4k,monitor,closeup",
        description: "4K Monitor: High-quality 4k monitor designed for everyday use with excellent durability and comfort.",
        price: 44899,
        category: "Electronics",
        subCategory: "Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Home Router Plus",
        image1: "https://source.unsplash.com/600x600/?home,router",
        image2: "https://source.unsplash.com/600x600/?home,router,product",
        image3: "https://source.unsplash.com/600x600/?home,router,studio",
        image4: "https://source.unsplash.com/600x600/?home,router,closeup",
        description: "Home Router Plus: High-quality home router designed for everyday use with excellent durability and comfort.",
        price: 36849,
        category: "Electronics",
        subCategory: "Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Nonstick Pan Plus",
        image1: "https://source.unsplash.com/600x600/?nonstick,pan",
        image2: "https://source.unsplash.com/600x600/?nonstick,pan,product",
        image3: "https://source.unsplash.com/600x600/?nonstick,pan,studio",
        image4: "https://source.unsplash.com/600x600/?nonstick,pan,closeup",
        description: "Nonstick Pan Plus: High-quality nonstick pan designed for everyday use with excellent durability and comfort.",
        price: 3999,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Knife Set",
        image1: "https://source.unsplash.com/600x600/?knife,set",
        image2: "https://source.unsplash.com/600x600/?knife,set,product",
        image3: "https://source.unsplash.com/600x600/?knife,set,studio",
        image4: "https://source.unsplash.com/600x600/?knife,set,closeup",
        description: "Knife Set: High-quality knife set designed for everyday use with excellent durability and comfort.",
        price: 3249,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Cutting Board",
        image1: "https://source.unsplash.com/600x600/?cutting,board",
        image2: "https://source.unsplash.com/600x600/?cutting,board,product",
        image3: "https://source.unsplash.com/600x600/?cutting,board,studio",
        image4: "https://source.unsplash.com/600x600/?cutting,board,closeup",
        description: "Cutting Board: High-quality cutting board designed for everyday use with excellent durability and comfort.",
        price: 5149,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Kitchen Mixer - Classic",
        image1: "https://source.unsplash.com/600x600/?kitchen,mixer",
        image2: "https://source.unsplash.com/600x600/?kitchen,mixer,product",
        image3: "https://source.unsplash.com/600x600/?kitchen,mixer,studio",
        image4: "https://source.unsplash.com/600x600/?kitchen,mixer,closeup",
        description: "Kitchen Mixer - Classic: High-quality kitchen mixer designed for everyday use with excellent durability and comfort.",
        price: 2349,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Ceramic Dinner Set Plus",
        image1: "https://source.unsplash.com/600x600/?ceramic,dinner,set",
        image2: "https://source.unsplash.com/600x600/?ceramic,dinner,set,product",
        image3: "https://source.unsplash.com/600x600/?ceramic,dinner,set,studio",
        image4: "https://source.unsplash.com/600x600/?ceramic,dinner,set,closeup",
        description: "Ceramic Dinner Set Plus: High-quality ceramic dinner set designed for everyday use with excellent durability and comfort.",
        price: 8849,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Vacuum Cleaner Pro",
        image1: "https://source.unsplash.com/600x600/?vacuum,cleaner",
        image2: "https://source.unsplash.com/600x600/?vacuum,cleaner,product",
        image3: "https://source.unsplash.com/600x600/?vacuum,cleaner,studio",
        image4: "https://source.unsplash.com/600x600/?vacuum,cleaner,closeup",
        description: "Vacuum Cleaner Pro: High-quality vacuum cleaner designed for everyday use with excellent durability and comfort.",
        price: 8049,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Air Fryer",
        image1: "https://source.unsplash.com/600x600/?air,fryer",
        image2: "https://source.unsplash.com/600x600/?air,fryer,product",
        image3: "https://source.unsplash.com/600x600/?air,fryer,studio",
        image4: "https://source.unsplash.com/600x600/?air,fryer,closeup",
        description: "Air Fryer: High-quality air fryer designed for everyday use with excellent durability and comfort.",
        price: 7099,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Storage Jars",
        image1: "https://source.unsplash.com/600x600/?storage,jars",
        image2: "https://source.unsplash.com/600x600/?storage,jars,product",
        image3: "https://source.unsplash.com/600x600/?storage,jars,studio",
        image4: "https://source.unsplash.com/600x600/?storage,jars,closeup",
        description: "Storage Jars: High-quality storage jars designed for everyday use with excellent durability and comfort.",
        price: 2349,
        category: "Home & Kitchen",
        subCategory: "Storage",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Bed Sheet Set - Classic",
        image1: "https://source.unsplash.com/600x600/?bed,sheet,set",
        image2: "https://source.unsplash.com/600x600/?bed,sheet,set,product",
        image3: "https://source.unsplash.com/600x600/?bed,sheet,set,studio",
        image4: "https://source.unsplash.com/600x600/?bed,sheet,set,closeup",
        description: "Bed Sheet Set - Classic: High-quality bed sheet set designed for everyday use with excellent durability and comfort.",
        price: 8449,
        category: "Home & Kitchen",
        subCategory: "Bedding",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Coffee Maker",
        image1: "https://source.unsplash.com/600x600/?coffee,maker",
        image2: "https://source.unsplash.com/600x600/?coffee,maker,product",
        image3: "https://source.unsplash.com/600x600/?coffee,maker,studio",
        image4: "https://source.unsplash.com/600x600/?coffee,maker,closeup",
        description: "Coffee Maker: High-quality coffee maker designed for everyday use with excellent durability and comfort.",
        price: 3099,
        category: "Home & Kitchen",
        subCategory: "Cookware",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Face Cream",
        image1: "https://source.unsplash.com/600x600/?face,cream",
        image2: "https://source.unsplash.com/600x600/?face,cream,product",
        image3: "https://source.unsplash.com/600x600/?face,cream,studio",
        image4: "https://source.unsplash.com/600x600/?face,cream,closeup",
        description: "Face Cream: High-quality face cream designed for everyday use with excellent durability and comfort.",
        price: 549,
        category: "Beauty & Health",
        subCategory: "Skincare",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Lipstick Pro",
        image1: "https://source.unsplash.com/600x600/?lipstick",
        image2: "https://source.unsplash.com/600x600/?lipstick,product",
        image3: "https://source.unsplash.com/600x600/?lipstick,studio",
        image4: "https://source.unsplash.com/600x600/?lipstick,closeup",
        description: "Lipstick Pro: High-quality lipstick designed for everyday use with excellent durability and comfort.",
        price: 2199,
        category: "Beauty & Health",
        subCategory: "Makeup",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Hair Oil Pro",
        image1: "https://source.unsplash.com/600x600/?hair,oil",
        image2: "https://source.unsplash.com/600x600/?hair,oil,product",
        image3: "https://source.unsplash.com/600x600/?hair,oil,studio",
        image4: "https://source.unsplash.com/600x600/?hair,oil,closeup",
        description: "Hair Oil Pro: High-quality hair oil designed for everyday use with excellent durability and comfort.",
        price: 1549,
        category: "Beauty & Health",
        subCategory: "Haircare",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Shampoo",
        image1: "https://source.unsplash.com/600x600/?shampoo",
        image2: "https://source.unsplash.com/600x600/?shampoo,product",
        image3: "https://source.unsplash.com/600x600/?shampoo,studio",
        image4: "https://source.unsplash.com/600x600/?shampoo,closeup",
        description: "Shampoo: High-quality shampoo designed for everyday use with excellent durability and comfort.",
        price: 3799,
        category: "Beauty & Health",
        subCategory: "Haircare",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Perfume",
        image1: "https://source.unsplash.com/600x600/?perfume",
        image2: "https://source.unsplash.com/600x600/?perfume,product",
        image3: "https://source.unsplash.com/600x600/?perfume,studio",
        image4: "https://source.unsplash.com/600x600/?perfume,closeup",
        description: "Perfume: High-quality perfume designed for everyday use with excellent durability and comfort.",
        price: 2199,
        category: "Beauty & Health",
        subCategory: "Fragrance",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Premium Vitamin Supplements",
        image1: "https://source.unsplash.com/600x600/?vitamin,supplements",
        image2: "https://source.unsplash.com/600x600/?vitamin,supplements,product",
        image3: "https://source.unsplash.com/600x600/?vitamin,supplements,studio",
        image4: "https://source.unsplash.com/600x600/?vitamin,supplements,closeup",
        description: "Premium Vitamin Supplements: High-quality vitamin supplements designed for everyday use with excellent durability and comfort.",
        price: 2699,
        category: "Beauty & Health",
        subCategory: "Wellness",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Sunscreen",
        image1: "https://source.unsplash.com/600x600/?sunscreen",
        image2: "https://source.unsplash.com/600x600/?sunscreen,product",
        image3: "https://source.unsplash.com/600x600/?sunscreen,studio",
        image4: "https://source.unsplash.com/600x600/?sunscreen,closeup",
        description: "Sunscreen: High-quality sunscreen designed for everyday use with excellent durability and comfort.",
        price: 4299,
        category: "Beauty & Health",
        subCategory: "Skincare",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Face Wash - Classic",
        image1: "https://source.unsplash.com/600x600/?face,wash",
        image2: "https://source.unsplash.com/600x600/?face,wash,product",
        image3: "https://source.unsplash.com/600x600/?face,wash,studio",
        image4: "https://source.unsplash.com/600x600/?face,wash,closeup",
        description: "Face Wash - Classic: High-quality face wash designed for everyday use with excellent durability and comfort.",
        price: 1049,
        category: "Beauty & Health",
        subCategory: "Skincare",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Moisturizer (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?moisturizer",
        image2: "https://source.unsplash.com/600x600/?moisturizer,product",
        image3: "https://source.unsplash.com/600x600/?moisturizer,studio",
        image4: "https://source.unsplash.com/600x600/?moisturizer,closeup",
        description: "Moisturizer (2025 Model): High-quality moisturizer designed for everyday use with excellent durability and comfort.",
        price: 3599,
        category: "Beauty & Health",
        subCategory: "Skincare",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Makeup Kit (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?makeup,kit",
        image2: "https://source.unsplash.com/600x600/?makeup,kit,product",
        image3: "https://source.unsplash.com/600x600/?makeup,kit,studio",
        image4: "https://source.unsplash.com/600x600/?makeup,kit,closeup",
        description: "Makeup Kit (2025 Model): High-quality makeup kit designed for everyday use with excellent durability and comfort.",
        price: 2899,
        category: "Beauty & Health",
        subCategory: "Makeup",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Cricket Bat",
        image1: "https://source.unsplash.com/600x600/?cricket,bat",
        image2: "https://source.unsplash.com/600x600/?cricket,bat,product",
        image3: "https://source.unsplash.com/600x600/?cricket,bat,studio",
        image4: "https://source.unsplash.com/600x600/?cricket,bat,closeup",
        description: "Cricket Bat: High-quality cricket bat designed for everyday use with excellent durability and comfort.",
        price: 5399,
        category: "Sports & Outdoors",
        subCategory: "Sports Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Yoga Mat Plus",
        image1: "https://source.unsplash.com/600x600/?yoga,mat",
        image2: "https://source.unsplash.com/600x600/?yoga,mat,product",
        image3: "https://source.unsplash.com/600x600/?yoga,mat,studio",
        image4: "https://source.unsplash.com/600x600/?yoga,mat,closeup",
        description: "Yoga Mat Plus: High-quality yoga mat designed for everyday use with excellent durability and comfort.",
        price: 6799,
        category: "Sports & Outdoors",
        subCategory: "Fitness Equipment",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Running Shoes Pro",
        image1: "https://source.unsplash.com/600x600/?running,shoes",
        image2: "https://source.unsplash.com/600x600/?running,shoes,product",
        image3: "https://source.unsplash.com/600x600/?running,shoes,studio",
        image4: "https://source.unsplash.com/600x600/?running,shoes,closeup",
        description: "Running Shoes Pro: High-quality running shoes designed for everyday use with excellent durability and comfort.",
        price: 11299,
        category: "Sports & Outdoors",
        subCategory: "Athletic Wear",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Fitness Tracker Plus",
        image1: "https://source.unsplash.com/600x600/?fitness,tracker",
        image2: "https://source.unsplash.com/600x600/?fitness,tracker,product",
        image3: "https://source.unsplash.com/600x600/?fitness,tracker,studio",
        image4: "https://source.unsplash.com/600x600/?fitness,tracker,closeup",
        description: "Fitness Tracker Plus: High-quality fitness tracker designed for everyday use with excellent durability and comfort.",
        price: 10399,
        category: "Sports & Outdoors",
        subCategory: "Fitness Equipment",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Bicycle Helmet",
        image1: "https://source.unsplash.com/600x600/?bicycle,helmet",
        image2: "https://source.unsplash.com/600x600/?bicycle,helmet,product",
        image3: "https://source.unsplash.com/600x600/?bicycle,helmet,studio",
        image4: "https://source.unsplash.com/600x600/?bicycle,helmet,closeup",
        description: "Bicycle Helmet: High-quality bicycle helmet designed for everyday use with excellent durability and comfort.",
        price: 7899,
        category: "Sports & Outdoors",
        subCategory: "Sports Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Premium Badminton Racket",
        image1: "https://source.unsplash.com/600x600/?badminton,racket",
        image2: "https://source.unsplash.com/600x600/?badminton,racket,product",
        image3: "https://source.unsplash.com/600x600/?badminton,racket,studio",
        image4: "https://source.unsplash.com/600x600/?badminton,racket,closeup",
        description: "Premium Badminton Racket: High-quality badminton racket designed for everyday use with excellent durability and comfort.",
        price: 7899,
        category: "Sports & Outdoors",
        subCategory: "Sports Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Camping Tent",
        image1: "https://source.unsplash.com/600x600/?camping,tent",
        image2: "https://source.unsplash.com/600x600/?camping,tent,product",
        image3: "https://source.unsplash.com/600x600/?camping,tent,studio",
        image4: "https://source.unsplash.com/600x600/?camping,tent,closeup",
        description: "Camping Tent: High-quality camping tent designed for everyday use with excellent durability and comfort.",
        price: 7049,
        category: "Sports & Outdoors",
        subCategory: "Camping Gear",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Dumbbell Set (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?dumbbell,set",
        image2: "https://source.unsplash.com/600x600/?dumbbell,set,product",
        image3: "https://source.unsplash.com/600x600/?dumbbell,set,studio",
        image4: "https://source.unsplash.com/600x600/?dumbbell,set,closeup",
        description: "Dumbbell Set (2025 Model): High-quality dumbbell set designed for everyday use with excellent durability and comfort.",
        price: 11299,
        category: "Sports & Outdoors",
        subCategory: "Fitness Equipment",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Sports Jersey",
        image1: "https://source.unsplash.com/600x600/?sports,jersey",
        image2: "https://source.unsplash.com/600x600/?sports,jersey,product",
        image3: "https://source.unsplash.com/600x600/?sports,jersey,studio",
        image4: "https://source.unsplash.com/600x600/?sports,jersey,closeup",
        description: "Sports Jersey: High-quality sports jersey designed for everyday use with excellent durability and comfort.",
        price: 8999,
        category: "Sports & Outdoors",
        subCategory: "Athletic Wear",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Water Bottle",
        image1: "https://source.unsplash.com/600x600/?water,bottle",
        image2: "https://source.unsplash.com/600x600/?water,bottle,product",
        image3: "https://source.unsplash.com/600x600/?water,bottle,studio",
        image4: "https://source.unsplash.com/600x600/?water,bottle,closeup",
        description: "Water Bottle: High-quality water bottle designed for everyday use with excellent durability and comfort.",
        price: 8999,
        category: "Sports & Outdoors",
        subCategory: "Sports Accessories",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Fiction Novel",
        image1: "https://source.unsplash.com/600x600/?fiction,novel",
        image2: "https://source.unsplash.com/600x600/?fiction,novel,product",
        image3: "https://source.unsplash.com/600x600/?fiction,novel,studio",
        image4: "https://source.unsplash.com/600x600/?fiction,novel,closeup",
        description: "Fiction Novel: High-quality fiction novel designed for everyday use with excellent durability and comfort.",
        price: 1299,
        category: "Books & Media",
        subCategory: "Fiction",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Programming Book - Classic",
        image1: "https://source.unsplash.com/600x600/?programming,book",
        image2: "https://source.unsplash.com/600x600/?programming,book,product",
        image3: "https://source.unsplash.com/600x600/?programming,book,studio",
        image4: "https://source.unsplash.com/600x600/?programming,book,closeup",
        description: "Programming Book - Classic: High-quality programming book designed for everyday use with excellent durability and comfort.",
        price: 249,
        category: "Books & Media",
        subCategory: "Educational",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Self Help Book Plus",
        image1: "https://source.unsplash.com/600x600/?self,help,book",
        image2: "https://source.unsplash.com/600x600/?self,help,book,product",
        image3: "https://source.unsplash.com/600x600/?self,help,book,studio",
        image4: "https://source.unsplash.com/600x600/?self,help,book,closeup",
        description: "Self Help Book Plus: High-quality self help book designed for everyday use with excellent durability and comfort.",
        price: 799,
        category: "Books & Media",
        subCategory: "Non-Fiction",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Kids Story Book - Classic",
        image1: "https://source.unsplash.com/600x600/?kids,story,book",
        image2: "https://source.unsplash.com/600x600/?kids,story,book,product",
        image3: "https://source.unsplash.com/600x600/?kids,story,book,studio",
        image4: "https://source.unsplash.com/600x600/?kids,story,book,closeup",
        description: "Kids Story Book - Classic: High-quality kids story book designed for everyday use with excellent durability and comfort.",
        price: 899,
        category: "Books & Media",
        subCategory: "Fiction",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Cookbook",
        image1: "https://source.unsplash.com/600x600/?cookbook",
        image2: "https://source.unsplash.com/600x600/?cookbook,product",
        image3: "https://source.unsplash.com/600x600/?cookbook,studio",
        image4: "https://source.unsplash.com/600x600/?cookbook,closeup",
        description: "Cookbook: High-quality cookbook designed for everyday use with excellent durability and comfort.",
        price: 899,
        category: "Books & Media",
        subCategory: "Non-Fiction",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "History Book",
        image1: "https://source.unsplash.com/600x600/?history,book",
        image2: "https://source.unsplash.com/600x600/?history,book,product",
        image3: "https://source.unsplash.com/600x600/?history,book,studio",
        image4: "https://source.unsplash.com/600x600/?history,book,closeup",
        description: "History Book: High-quality history book designed for everyday use with excellent durability and comfort.",
        price: 1449,
        category: "Books & Media",
        subCategory: "Educational",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Science Textbook",
        image1: "https://source.unsplash.com/600x600/?science,textbook",
        image2: "https://source.unsplash.com/600x600/?science,textbook,product",
        image3: "https://source.unsplash.com/600x600/?science,textbook,studio",
        image4: "https://source.unsplash.com/600x600/?science,textbook,closeup",
        description: "Science Textbook: High-quality science textbook designed for everyday use with excellent durability and comfort.",
        price: 1399,
        category: "Books & Media",
        subCategory: "Educational",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Poetry Collection",
        image1: "https://source.unsplash.com/600x600/?poetry,collection",
        image2: "https://source.unsplash.com/600x600/?poetry,collection,product",
        image3: "https://source.unsplash.com/600x600/?poetry,collection,studio",
        image4: "https://source.unsplash.com/600x600/?poetry,collection,closeup",
        description: "Poetry Collection: High-quality poetry collection designed for everyday use with excellent durability and comfort.",
        price: 1049,
        category: "Books & Media",
        subCategory: "Fiction",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Comic Book - Classic",
        image1: "https://source.unsplash.com/600x600/?comic,book",
        image2: "https://source.unsplash.com/600x600/?comic,book,product",
        image3: "https://source.unsplash.com/600x600/?comic,book,studio",
        image4: "https://source.unsplash.com/600x600/?comic,book,closeup",
        description: "Comic Book - Classic: High-quality comic book designed for everyday use with excellent durability and comfort.",
        price: 1299,
        category: "Books & Media",
        subCategory: "Comics",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Business Book (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?business,book",
        image2: "https://source.unsplash.com/600x600/?business,book,product",
        image3: "https://source.unsplash.com/600x600/?business,book,studio",
        image4: "https://source.unsplash.com/600x600/?business,book,closeup",
        description: "Business Book (2025 Model): High-quality business book designed for everyday use with excellent durability and comfort.",
        price: 99,
        category: "Books & Media",
        subCategory: "Non-Fiction",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Premium Building Blocks",
        image1: "https://source.unsplash.com/600x600/?building,blocks",
        image2: "https://source.unsplash.com/600x600/?building,blocks,product",
        image3: "https://source.unsplash.com/600x600/?building,blocks,studio",
        image4: "https://source.unsplash.com/600x600/?building,blocks,closeup",
        description: "Premium Building Blocks: High-quality building blocks designed for everyday use with excellent durability and comfort.",
        price: 299,
        category: "Toys & Games",
        subCategory: "Educational Toys",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Remote Car - Classic",
        image1: "https://source.unsplash.com/600x600/?remote,car",
        image2: "https://source.unsplash.com/600x600/?remote,car,product",
        image3: "https://source.unsplash.com/600x600/?remote,car,studio",
        image4: "https://source.unsplash.com/600x600/?remote,car,closeup",
        description: "Remote Car - Classic: High-quality remote car designed for everyday use with excellent durability and comfort.",
        price: 2149,
        category: "Toys & Games",
        subCategory: "Action Figures",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Puzzle Game Plus",
        image1: "https://source.unsplash.com/600x600/?puzzle,game",
        image2: "https://source.unsplash.com/600x600/?puzzle,game,product",
        image3: "https://source.unsplash.com/600x600/?puzzle,game,studio",
        image4: "https://source.unsplash.com/600x600/?puzzle,game,closeup",
        description: "Puzzle Game Plus: High-quality puzzle game designed for everyday use with excellent durability and comfort.",
        price: 3799,
        category: "Toys & Games",
        subCategory: "Puzzles",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Board Game",
        image1: "https://source.unsplash.com/600x600/?board,game",
        image2: "https://source.unsplash.com/600x600/?board,game,product",
        image3: "https://source.unsplash.com/600x600/?board,game,studio",
        image4: "https://source.unsplash.com/600x600/?board,game,closeup",
        description: "Board Game: High-quality board game designed for everyday use with excellent durability and comfort.",
        price: 699,
        category: "Toys & Games",
        subCategory: "Board Games",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Plush Toy",
        image1: "https://source.unsplash.com/600x600/?plush,toy",
        image2: "https://source.unsplash.com/600x600/?plush,toy,product",
        image3: "https://source.unsplash.com/600x600/?plush,toy,studio",
        image4: "https://source.unsplash.com/600x600/?plush,toy,closeup",
        description: "Plush Toy: High-quality plush toy designed for everyday use with excellent durability and comfort.",
        price: 599,
        category: "Toys & Games",
        subCategory: "Action Figures",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Educational Toy",
        image1: "https://source.unsplash.com/600x600/?educational,toy",
        image2: "https://source.unsplash.com/600x600/?educational,toy,product",
        image3: "https://source.unsplash.com/600x600/?educational,toy,studio",
        image4: "https://source.unsplash.com/600x600/?educational,toy,closeup",
        description: "Educational Toy: High-quality educational toy designed for everyday use with excellent durability and comfort.",
        price: 3599,
        category: "Toys & Games",
        subCategory: "Educational Toys",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Lego Set",
        image1: "https://source.unsplash.com/600x600/?lego,set",
        image2: "https://source.unsplash.com/600x600/?lego,set,product",
        image3: "https://source.unsplash.com/600x600/?lego,set,studio",
        image4: "https://source.unsplash.com/600x600/?lego,set,closeup",
        description: "Lego Set: High-quality lego set designed for everyday use with excellent durability and comfort.",
        price: 999,
        category: "Toys & Games",
        subCategory: "Educational Toys",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Action Figure",
        image1: "https://source.unsplash.com/600x600/?action,figure",
        image2: "https://source.unsplash.com/600x600/?action,figure,product",
        image3: "https://source.unsplash.com/600x600/?action,figure,studio",
        image4: "https://source.unsplash.com/600x600/?action,figure,closeup",
        description: "Action Figure: High-quality action figure designed for everyday use with excellent durability and comfort.",
        price: 3699,
        category: "Toys & Games",
        subCategory: "Action Figures",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Toy Train (2025 Model)",
        image1: "https://source.unsplash.com/600x600/?toy,train",
        image2: "https://source.unsplash.com/600x600/?toy,train,product",
        image3: "https://source.unsplash.com/600x600/?toy,train,studio",
        image4: "https://source.unsplash.com/600x600/?toy,train,closeup",
        description: "Toy Train (2025 Model): High-quality toy train designed for everyday use with excellent durability and comfort.",
        price: 4049,
        category: "Toys & Games",
        subCategory: "Action Figures",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      },
      {
        name: "Outdoor Swing Plus",
        image1: "https://source.unsplash.com/600x600/?outdoor,swing",
        image2: "https://source.unsplash.com/600x600/?outdoor,swing,product",
        image3: "https://source.unsplash.com/600x600/?outdoor,swing,studio",
        image4: "https://source.unsplash.com/600x600/?outdoor,swing,closeup",
        description: "Outdoor Swing Plus: High-quality outdoor swing designed for everyday use with excellent durability and comfort.",
        price: 3649,
        category: "Toys & Games",
        subCategory: "Outdoor Toys",
        sizes: [],
        date: Date.now(),
        bestseller: false,
        discount: 0,
        isManual: true
      }
    ];

    const result = await Product.insertMany(newProducts);
    console.log(`Added ${result.length} new products.`);

  } catch (err) {
    console.error('Addition error:', err);
  } finally {
    await mongoose.connection.close();
    process.exit(0);
  }
}

addNewProducts();
       